version: "3.9"

services:
  sabrina-main:
    build: .
    container_name: sabrina-main
    working_dir: /app/src/sabrina
    command: pdm run python main.py start
    volumes:
      - .:/app
    restart: always

  sabrina-cron:
    build: .
    container_name: sabrina-cron
    working_dir: /app/src/sabrina
    command: pdm run python main.py cron
    volumes:
      - .:/app
    restart: always
